CREATE TABLE service_items (
    id BIGSERIAL PRIMARY KEY,
    service_record_id BIGINT NOT NULL REFERENCES service_records(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    quantity INTEGER NOT NULL,
    cost DECIMAL(15, 2) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
